author: "Arafat Al Mahmud <arafat.almahmud89@gmail.com>"
category: "offline"
summary: "Send message to webhook for offline room users"
home: "https://github.com/arafat-al-mahmud/mod_muc_offline_post/tree/master"
url: "https://github.com/arafat-al-mahmud/mod_muc_offline_post.git"
